# Examples Copier Configuration
# This is a sample configuration - customize for your needs

source_repo: "mongodb/docs-realm"
source_branch: "main"

copy_rules:
  # Rule 1: Copy generated examples (matches actual API file paths)
  - name: "Copy generated examples"
    source_pattern:
      type: "regex"
      pattern: "^generated-examples/(?P<project>[^/]+)/(?P<rest>.+)$"
    targets:
      - repo: "mongodb/target-repo"
        branch: "main"
        path_transform: "examples/${project}/${rest}"
        commit_strategy:
          type: "pull_request"
          commit_message: "Update ${project} examples"
          pr_title: "Update ${project} examples"
          pr_body: "Automated update from ${source_repo}"
          auto_merge: false
        deprecation_check:
          enabled: true
          file: "deprecated_examples.json"

  # Rule 2: Copy all generated-examples files (fallback)
  - name: "Copy all generated examples"
    source_pattern:
      type: "prefix"
      pattern: "generated-examples/"
    targets:
      - repo: "mongodb/target-repo"
        branch: "main"
        path_transform: "docs/${path}"
        commit_strategy:
          type: "direct"
          commit_message: "Update examples from ${source_repo}"

