# Example YAML configuration for the GitHub Code Example Copier
# This file demonstrates the new pattern matching and path transformation features

source_repo: "mongodb/docs-code-examples"
source_branch: "main"

copy_rules:
  # Example 1: Simple prefix matching with recursive copy
  - name: "go-examples-basic"
    source_pattern:
      type: "prefix"
      pattern: "generated-examples/go"
    targets:
      - repo: "mongodb/docs"
        branch: "main"
        path_transform: "source/code-examples/go/${relative_path}"
        commit_strategy:
          type: "direct"
          commit_message: "Update Go code examples from ${source_repo}"
        deprecation_check:
          enabled: true
          file: "deprecated_examples.json"

  # Example 2: Glob pattern matching for specific file types
  - name: "python-examples-glob"
    source_pattern:
      type: "glob"
      pattern: "examples/**/*.py"
    targets:
      - repo: "mongodb/docs"
        branch: "main"
        path_transform: "source/code-examples/python/${filename}"
        commit_strategy:
          type: "pull_request"
          pr_title: "Update Python examples"
          pr_body: "Automated update of Python code examples from ${source_repo} (PR #${pr_number})"
          auto_merge: false
        deprecation_check:
          enabled: true

  # Example 3: Advanced regex pattern with variable extraction
  - name: "language-categorized-examples"
    source_pattern:
      type: "regex"
      pattern: "^examples/(?P<lang>[^/]+)/(?P<category>[^/]+)/(?P<file>.+)$"
    targets:
      # Target 1: Main docs repository
      - repo: "mongodb/docs"
        branch: "main"
        path_transform: "source/code-examples/${lang}/${category}/${file}"
        commit_strategy:
          type: "pull_request"
          pr_title: "Update ${lang} ${category} examples"
          pr_body: |
            Automated update of ${lang} examples in category: ${category}
            
            Files updated: ${file_count}
            Source: ${source_repo}
            PR: #${pr_number}
            Commit: ${commit_sha}
          auto_merge: false
        deprecation_check:
          enabled: true
          file: "deprecated_examples.json"
      
      # Target 2: Tutorials repository (different structure)
      - repo: "mongodb/tutorials"
        branch: "main"
        path_transform: "code/${lang}/${file}"
        commit_strategy:
          type: "direct"
          commit_message: "Update ${lang} tutorial code from ${source_repo}"

  # Example 4: Batch commit strategy for high-volume updates
  - name: "test-examples-batch"
    source_pattern:
      type: "glob"
      pattern: "tests/**/*.test.js"
    targets:
      - repo: "mongodb/test-examples"
        branch: "develop"
        path_transform: "examples/${filename}"
        commit_strategy:
          type: "batch"
          batch_size: 50
          commit_message: "Batch update of test examples (${file_count} files)"
        deprecation_check:
          enabled: false

  # Example 5: Non-main branch target for staging
  - name: "staging-examples"
    source_pattern:
      type: "prefix"
      pattern: "staging/"
    targets:
      - repo: "mongodb/docs"
        branch: "staging"
        path_transform: "source/staging/${relative_path}"
        commit_strategy:
          type: "pull_request"
          pr_title: "Update staging examples"
          auto_merge: true
        deprecation_check:
          enabled: true

