# Example Configuration with PR Template Support
# This demonstrates how to use use_pr_template to fetch and merge PR templates from target repos
#
# When use_pr_template: true, the service will:
# 1. Fetch the PR template from the target repo (.github/pull_request_template.md)
# 2. Place the template content FIRST (checklists, review guidelines)
# 3. Add a separator (---)
# 4. Append your configured pr_body (automation info)
#
# This ensures reviewers see the target repo's guidelines prominently.

source_repo: "mongodb/code-examples"
source_branch: "main"
batch_by_repo: false  # Create separate PRs for each rule

copy_rules:
  # Example 1: Use PR template from target repo
  - name: "go-examples-with-template"
    source_pattern:
      type: "prefix"
      pattern: "examples/go/"
    targets:
      - repo: "mongodb/docs"
        branch: "main"
        path_transform: "source/code-examples/go/${relative_path}"
        commit_strategy:
          type: "pull_request"
          pr_title: "Update Go examples"
          pr_body: |
            🤖 **Automated Update of Go Examples**
            
            **Source Information:**
            - Repository: ${source_repo}
            - Branch: ${source_branch}
            - PR: #${pr_number}
            - Commit: ${commit_sha}
            
            **Changes:**
            - Files updated: ${file_count}
            - Target branch: ${target_branch}
          use_pr_template: true  # Fetch and merge PR template from mongodb/docs
          auto_merge: false

  # Example 2: Different templates for different targets
  - name: "shared-examples"
    source_pattern:
      type: "regex"
      pattern: "^shared/(?P<lang>[^/]+)/(?P<file>.+)$"
    targets:
      # Target 1: Main docs - use their PR template
      - repo: "mongodb/docs"
        branch: "main"
        path_transform: "examples/${lang}/${file}"
        commit_strategy:
          type: "pull_request"
          pr_title: "Update ${lang} examples"
          pr_body: |
            Automated update of ${lang} examples
            
            Files: ${file_count}
          use_pr_template: true  # Use mongodb/docs template
          auto_merge: false
      
      # Target 2: Tutorials - use their different template
      - repo: "mongodb/tutorials"
        branch: "main"
        path_transform: "code/${lang}/${file}"
        commit_strategy:
          type: "pull_request"
          pr_title: "Update ${lang} tutorial code"
          pr_body: |
            Tutorial code update for ${lang}
            
            Source PR: #${pr_number}
          use_pr_template: true  # Use mongodb/tutorials template
          auto_merge: false

  # Example 3: Conditional template usage
  # Use template for production, skip for staging
  - name: "python-examples-production"
    source_pattern:
      type: "prefix"
      pattern: "examples/python/"
    targets:
      # Production: Use PR template for thorough review
      - repo: "mongodb/docs"
        branch: "main"
        path_transform: "source/code/python/${relative_path}"
        commit_strategy:
          type: "pull_request"
          pr_title: "Update Python examples (Production)"
          pr_body: |
            🚀 **Production Update**
            
            Files: ${file_count}
            Source: ${source_repo}
          use_pr_template: true  # Use template for production
          auto_merge: false
      
      # Staging: Skip template for faster iteration
      - repo: "mongodb/docs-staging"
        branch: "main"
        path_transform: "source/code/python/${relative_path}"
        commit_strategy:
          type: "pull_request"
          pr_title: "Update Python examples (Staging)"
          pr_body: |
            🧪 **Staging Update**
            
            Files: ${file_count}
          use_pr_template: false  # Skip template for staging
          auto_merge: true  # Auto-merge staging changes

  # Example 4: Rich PR body with template
  - name: "java-examples-detailed"
    source_pattern:
      type: "regex"
      pattern: "^examples/java/(?P<category>[^/]+)/(?P<file>.+)$"
    targets:
      - repo: "mongodb/java-driver"
        branch: "main"
        path_transform: "examples/${category}/${file}"
        commit_strategy:
          type: "pull_request"
          pr_title: "Update ${category} examples"
          pr_body: |
            # Automated Example Update
            
            ## Summary
            This PR updates Java code examples in the `${category}` category.
            
            ## Details
            - **Category:** ${category}
            - **Files Updated:** ${file_count}
            - **Source Repository:** ${source_repo}
            - **Source Branch:** ${source_branch}
            - **Source PR:** #${pr_number}
            - **Source Commit:** ${commit_sha}
            - **Target Branch:** ${target_branch}
            
            ## Changes
            These examples were automatically copied from the source repository.
            All files have been validated and are ready for review.
            
            ## Testing
            - [ ] Examples compile successfully
            - [ ] Examples run without errors
            - [ ] Documentation is up to date
            
            ---
            
            _This PR was automatically created by the Code Example Copier service._
          use_pr_template: true  # Template appears first, then this content
          auto_merge: false

  # Example 5: Minimal config with template
  - name: "typescript-examples-simple"
    source_pattern:
      type: "prefix"
      pattern: "examples/typescript/"
    targets:
      - repo: "mongodb/node-mongodb-native"
        branch: "main"
        path_transform: "examples/${relative_path}"
        commit_strategy:
          type: "pull_request"
          pr_title: "Update TypeScript examples"
          pr_body: "Automated update from ${source_repo} PR #${pr_number}"
          use_pr_template: true  # Template provides structure, this adds context
          auto_merge: false

  # Example 6: No template (traditional approach)
  - name: "rust-examples-no-template"
    source_pattern:
      type: "prefix"
      pattern: "examples/rust/"
    targets:
      - repo: "mongodb/mongo-rust-driver"
        branch: "main"
        path_transform: "examples/${relative_path}"
        commit_strategy:
          type: "pull_request"
          pr_title: "Update Rust examples"
          pr_body: |
            ## Automated Update
            
            This PR updates Rust code examples.
            
            **Details:**
            - Files: ${file_count}
            - Source: ${source_repo}
            - PR: #${pr_number}
            
            **Review Checklist:**
            - [ ] Examples compile
            - [ ] Tests pass
            - [ ] Documentation updated
          use_pr_template: false  # Use only this configured body
          auto_merge: false

  # Example 7: Direct commit (template not applicable)
  - name: "config-files-direct"
    source_pattern:
      type: "glob"
      pattern: "config/**/*.yaml"
    targets:
      - repo: "mongodb/docs-config"
        branch: "main"
        path_transform: "examples/${matched_pattern}"
        commit_strategy:
          type: "direct"  # Direct commits don't use PR templates
          commit_message: "Update config files from ${source_repo}"

